version: '3.8'
services:
  service-back:
    image: tinkoff-ab-hw-2-1-back:0.0.1
    container_name: backend-service
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/tinkoff_hw_db
  db:
    image: postgres:15.3-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tinkoff_hw_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  db-data:

